import type { Metadata } from "next";
import "./globals.css";
import { NaverMapScript } from "@/components/features/map/NaverMapScript";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const ncpKeyId = process.env.NEXT_PUBLIC_NAVER_MAP_CLIENT_ID ?? "";

  return (
    <html lang="en">
      <body>
        <NaverMapScript ncpKeyId={ncpKeyId} />
        {children}
      </body>
    </html>
  );
}
